2023-04-03 02:40:29.776171: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-03 02:40:36.814592: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/mcy/conus2_ml/train_XE.py", line 508, in <module>
    history = model.fit(Xdata_train,Ydata_train,epochs=nepochs,\
  File "/home/mcy/mambaforge/envs/tf_gpu/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_file32tayxjs.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/tmp/__autograph_generated_filemzei7ruq.py", line 19, in tf__loss
    xentropy_tensor = ag__.ld(filtered_target_tensor) * ag__.converted_call(ag__.ld(_log2), (ag__.ld(filtered_prediction_tensor),), None, fscope) + (1.0 - ag__.ld(filtered_target_tensor)) * ag__.converted_call(ag__.ld(_log2), (1.0 - ag__.ld(filtered_prediction_tensor),), None, fscope)
ValueError: in user code:

    File "/home/mcy/mambaforge/envs/tf_gpu/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/home/mcy/conus2_ml/custom_model_elements.py", line 244, in loss  *
        xentropy_tensor = (

    ValueError: Dimensions must be equal, but are 256 and 32 for '{{node loss/mul_2}} = Mul[T=DT_FLOAT](loss/mul, loss/truediv)' with input shapes: [1,256,256,256], [?,256,256,32].

slurmstepd: error: acct_gather_profile/influxdb _send_data: curl_easy_perform failed to send data (discarded). Reason: Couldn't resolve host name
